package io.aduhtkjm.mekanismheated.block.phasechange;

import io.aduhtkjm.mekanismheated.content.phasechange.PhaseChangeTier;
import io.aduhtkjm.mekanismheated.tile.TileEntityPhaseChangeBlock;
import mekanism.common.block.prefab.BlockTile;
import mekanism.common.content.blocktype.Machine;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;
import org.lwjgl.system.NonnullDefault;

/**
 * One of the three phase-change blocks. The block only carries the tier (and therefore the melting point); the heat
 * behaviour lives in {@link TileEntityPhaseChangeBlock} and {@link io.aduhtkjm.mekanismheated.content.phasechange.PhaseChangeHeatCapacitor}.
 * <p>
 * The shape is the union of the cuboids in the generated block model: full 16x16 slabs for the "large" layers and
 * centred 12x12 slabs for the "small" ones. It is the same for every tier.
 */
@NonnullDefault
public class PhaseChangeBlock extends BlockTile<TileEntityPhaseChangeBlock, Machine<TileEntityPhaseChangeBlock>> {

    // Generated by scripts/phase_change_block_model.py (11 merged cuboids). The silhouette is symmetric around the Y
    // axis, so no rotation is needed.
    private static final VoxelShape SHAPE = Shapes.or(
            Block.box(0.0D, 0.0D, 0.0D, 16.0D, 2.0D, 16.0D),
            Block.box(2.0D, 2.0D, 2.0D, 14.0D, 3.0D, 14.0D),
            Block.box(0.0D, 3.0D, 0.0D, 16.0D, 5.0D, 16.0D),
            Block.box(2.0D, 5.0D, 2.0D, 14.0D, 6.0D, 14.0D),
            Block.box(0.0D, 6.0D, 0.0D, 16.0D, 7.0D, 16.0D),
            Block.box(2.0D, 7.0D, 2.0D, 14.0D, 9.0D, 14.0D),
            Block.box(0.0D, 9.0D, 0.0D, 16.0D, 10.0D, 16.0D),
            Block.box(2.0D, 10.0D, 2.0D, 14.0D, 11.0D, 14.0D),
            Block.box(0.0D, 11.0D, 0.0D, 16.0D, 13.0D, 16.0D),
            Block.box(2.0D, 13.0D, 2.0D, 14.0D, 14.0D, 14.0D),
            Block.box(0.0D, 14.0D, 0.0D, 16.0D, 16.0D, 16.0D)
    ).optimize();

    private final PhaseChangeTier tier;

    public PhaseChangeBlock(PhaseChangeTier tier, Machine<TileEntityPhaseChangeBlock> type, BlockBehaviour.Properties properties) {
        super(type, properties);
        this.tier = tier;
    }

    public PhaseChangeTier getTier() {
        return tier;
    }

    @Override
    protected VoxelShape getShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
        return SHAPE;
    }

    @Override
    protected VoxelShape getCollisionShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
        return SHAPE;
    }

    @Override
    protected VoxelShape getOcclusionShape(BlockState state, BlockGetter level, BlockPos pos) {
        return SHAPE;
    }

    @Override
    protected boolean useShapeForLightOcclusion(BlockState state) {
        return true;
    }
}
