#!/usr/bin/env python3
"""Generate the phase-change blocks' models, blockstates and VoxelShape constants.

All three phase-change blocks (low / medium / high) share a single silhouette. It is
described as a stack of 16 one-pixel layers, each of which is either "large" (a full
16x16 footprint) or "small" (a centred 12x12 footprint). Adjacent layers of the same
size are merged into a single cuboid, so the emitted models contain one element per run
of equal layers rather than one per layer.

The same merged cuboids are printed as Java ``VoxelShape`` constants; paste the block
into ``PhaseChangeBlock`` (the shape is rotationally symmetric, so one constant is
enough).

Run from the repository root:

    python scripts/phase_change_block_model.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS = REPO_ROOT / "src/main/resources/assets/mekanismheated"
BLOCK_MODELS = ASSETS / "models/block"
ITEM_MODELS = ASSETS / "models/item"
BLOCKSTATES = ASSETS / "blockstates"

# Layer 0 is the bottom of the block, layer 15 the top.
LARGE = "large"
SMALL = "small"
LAYERS = (
    LARGE, LARGE, SMALL, LARGE, LARGE, SMALL, LARGE, SMALL,
    SMALL, LARGE, SMALL, LARGE, LARGE, SMALL, LARGE, LARGE,
)

# A "large" layer fills the whole 16x16 footprint; a "small" layer is inset by two pixels
# on every horizontal side (12x12), so the two are centre-aligned.
INSET = {LARGE: 0, SMALL: 2}

TIERS = ("low", "medium", "high")


def block_name(tier: str) -> str:
    return f"phase_change_block_{tier}"


def merged_boxes() -> list[tuple[str, int, int]]:
    """Merge runs of adjacent equal-sized layers into (size, y_min, y_max) cuboids."""
    boxes: list[tuple[str, int, int]] = []
    run_start = 0
    for y in range(1, len(LAYERS) + 1):
        if y == len(LAYERS) or LAYERS[y] != LAYERS[run_start]:
            boxes.append((LAYERS[run_start], run_start, y))
            run_start = y
    return boxes


def bounds(size: str, y_min: int, y_max: int) -> tuple[int, int, int, int, int, int]:
    inset = INSET[size]
    return inset, y_min, inset, 16 - inset, y_max, 16 - inset


def element(size: str, y_min: int, y_max: int) -> dict:
    min_x, min_y, min_z, max_x, max_y, max_z = bounds(size, y_min, y_max)
    faces = {face: {"texture": "#all"} for face in ("down", "up", "north", "south", "west", "east")}
    return {"from": [min_x, min_y, min_z], "to": [max_x, max_y, max_z], "faces": faces}


def block_model(tier: str) -> dict:
    return {
        # Inherit the standard block display transforms and the "particle" texture alias.
        "parent": "block/cube_all",
        "textures": {"all": f"mekanismheated:block/{block_name(tier)}"},
        "elements": [element(size, y_min, y_max) for size, y_min, y_max in merged_boxes()],
    }


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(REPO_ROOT)}")


def java_box(size: str, y_min: int, y_max: int) -> str:
    coordinates = [float(value) for value in bounds(size, y_min, y_max)]
    arguments = ", ".join(f"{value:.1f}D" for value in coordinates)
    return f"Block.box({arguments})"


def print_shape() -> None:
    boxes = merged_boxes()
    print()
    print(f"// Generated by scripts/phase_change_block_model.py ({len(boxes)} merged cuboids)")
    print("private static final VoxelShape SHAPE = Shapes.or(")
    for index, (size, y_min, y_max) in enumerate(boxes):
        suffix = "," if index < len(boxes) - 1 else ""
        print(f"        {java_box(size, y_min, y_max)}{suffix}")
    print(").optimize();")


def main() -> None:
    for tier in TIERS:
        name = block_name(tier)
        write_json(BLOCK_MODELS / f"{name}.json", block_model(tier))
        write_json(ITEM_MODELS / f"{name}.json", {"parent": f"mekanismheated:block/{name}"})
        write_json(BLOCKSTATES / f"{name}.json",
                   {"variants": {"": {"model": f"mekanismheated:block/{name}"}}})
    print_shape()


if __name__ == "__main__":
    main()
